import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { changeValue } from '../scripts/main'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Typescript Learning</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.holder}>
          <h1>Hello, World!</h1>
          <p id="para">This is typescript!</p>
          <button className={styles.btn} onClick={changeValue}>Click Me!</button>
        </div>
      </main>
    </div>
  )
}

export default Home